name: AWS Lambda Build, Testing, and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  AWS_REGION: 'us-east-2' # Define AWS region here
  LAMBDA_FUNCTION_NAME: 'wdwebsolutions-contact-backend-4e93dbe' # Lambda function name
  LAMBDA_CODE_PATH: 'lambda' # Path to the Lambda function code

jobs:
  run-lambda-tests:
    runs-on: ubuntu-latest
    name: Run Python Unit Tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install test dependencies
        run: |
          cd ${{ env.LAMBDA_CODE_PATH }}
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd ${{ env.LAMBDA_CODE_PATH }}
          python -m unittest discover -s tests

  deploy-lambda:
    needs: run-lambda-tests
    runs-on: ubuntu-latest
    name: Deploy Lambda Function
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ vars.LAMBDA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.LAMBDA_AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          cd ${{ env.LAMBDA_CODE_PATH }}
          pip install -r requirements.txt -t build/
      - name: Package Lambda function
        run: |
          cd ${{ env.LAMBDA_CODE_PATH }}
          cp main.py build/
          cp -R helpers/ build/
          cd build
          zip -r ../function.zip .
          pwd
          ls -la  # This will list all files in the current directory
          cd ..
          ls -la  # This will list all files in the current directory

      - name: Deploy to Lambda
        run: |
          cd ${{ env.LAMBDA_CODE_PATH }}
          pwd
          ls -la
          aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --zip-file fileb://function.zip
